In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

In [3]:
train_data=pd.read_csv(r'C:\Users\neera\OneDrive\Desktop\Projects\Analyze this\development_dataset.csv')
leader_data=pd.read_csv(r'C:\Users\neera\OneDrive\Desktop\Projects\Analyze this\leaderboard_dataset.csv')

In [4]:
train_data.head()

VAR1        VAR2      VAR3        VAR4        VAR5      VAR6      VAR7  \
0     1  828.235294  0.138889  321.428571  625.911006  1.818182  1.081550   
1     2  911.764706  0.027778         NaN  611.574748  8.181818  1.344479   
2     3  962.352941  0.833333   35.714286  615.825381  8.181818  0.720796   
3     4  892.941177       NaN         NaN  638.076431  9.090909  0.820218   
4     5  914.117647  0.083333         NaN  626.514988  5.181818  1.372928   

         VAR8       VAR9      VAR10  ...       VAR12  VAR13  VAR14 VAR15  \
0  198.113469        NaN  58.632548  ...  100.083403    1.0      1   1.0   
1  198.600020  22.086661        NaN  ...   15.012510    NaN      1   NaN   
2  197.267767        NaN  58.632548  ...  210.175146   10.0      1  10.0   
3  197.355744   4.363431  58.632548  ...         NaN    NaN      1   NaN   
4  198.790477  85.938202  58.632548  ...  210.175146    NaN      .   NaN   

      VAR16  VAR17  VAR18  VAR19       VAR20   VAR21  
0  1.540594    NaN      1      0  100.104991     Low  
1  1.614613    NaN      0      1  146.654045    High  
2  1.044599    NaN      0      0   98.249570  Medium  
3  1.145729    NaN      1      0  140.862306     Low  
4  1.558341    NaN      1      0  101.268503    High  

[5 rows x 21 columns]

In [5]:
train_data.describe()

VAR1          VAR2          VAR3          VAR4          VAR5  \
count  34000.000000  33039.000000  30615.000000  21506.000000  33999.000000   
mean   17000.500000    917.391603      1.119596    248.076201    631.571391   
std     9815.098913     50.222389     12.714724    241.167723     30.863288   
min        1.000000    730.588235      0.001333     18.928571    347.053355   
25%     8500.750000    882.352941      0.083333     71.428571    611.691167   
50%    17000.500000    924.705882      0.166667    142.857143    619.802909   
75%    25500.250000    956.470588      0.555556    357.142857    637.450565   
max    34000.000000   1000.000000   1000.000000   1000.000000   1000.000000   

               VAR6          VAR7          VAR8          VAR9         VAR10  \
count  30505.000000  33165.000000  33165.000000  18183.000000  29450.000000   
mean      15.290028      2.055295    200.007169     53.988554     56.497320   
std       29.123815      8.960891     11.282223     84.573655      6.861058   
min        0.005000      0.353228      0.000000      0.004278     13.028620   
25%        6.636364      0.691201    197.196716      8.784613     57.458373   
50%       10.000000      0.998093    197.912501     22.086661     58.632548   
75%       18.181818      1.735250    199.687427     58.559811     58.632548   
max      909.090818    681.582083   1000.000000    993.061289   1000.000000   

              VAR11         VAR12         VAR13         VAR15         VAR16  \
count  26435.000000  23498.000000  25478.000000  25976.000000  33134.000000   
mean       5.429062    117.283667     11.679589     12.453257      2.092006   
std       11.433905    120.628594     11.063966     12.084965      8.051804   
min        0.000693      0.834028      0.082667      0.133333      0.959315   
25%        0.638239     15.012510      5.666667      6.666667      1.040125   
50%        2.098360     80.066722     10.000000     10.000000      1.262747   
75%        6.043179    193.494579     15.333333     16.400000      1.827486   
max      824.334457   1000.000000    775.000000    775.000000   1000.000000   

              VAR17         VAR18         VAR19         VAR20  
count  11806.000000  34000.000000  34000.000000  34000.000000  
mean     821.281092      0.400029      0.298059    161.355950  
std      262.338240      0.684850      0.457412    123.231136  
min        0.130000      0.000000      0.000000      0.000000  
25%      732.662500      0.000000      0.000000    104.385542  
50%      965.345000      0.000000      0.000000    117.493115  
75%     1000.000000      1.000000      1.000000    159.446213  
max     1000.000000     14.000000      1.000000   1000.000000

In [6]:
train_data.isnull().sum()

VAR1         0
VAR2       961
VAR3      3385
VAR4     12494
VAR5         1
VAR6      3495
VAR7       835
VAR8       835
VAR9     15817
VAR10     4550
VAR11     7565
VAR12    10502
VAR13     8522
VAR14        0
VAR15     8024
VAR16      866
VAR17    22194
VAR18        0
VAR19        0
VAR20        0
VAR21        0
dtype: int64

In [7]:
train_data['VAR2'].fillna(train_data['VAR2'].median(),inplace=True)
train_data['VAR3'].fillna(train_data['VAR3'].median(),inplace=True)
train_data['VAR4'].fillna(train_data['VAR4'].median(),inplace=True)
train_data['VAR5'].fillna(train_data['VAR5'].median(),inplace=True)
train_data['VAR6'].fillna(train_data['VAR6'].median(),inplace=True)
train_data['VAR7'].fillna(train_data['VAR7'].median(),inplace=True)
train_data['VAR8'].fillna(train_data['VAR8'].median(),inplace=True)
train_data['VAR9'].fillna(train_data['VAR9'].median(),inplace=True)
train_data['VAR10'].fillna(train_data['VAR10'].median(),inplace=True)
train_data['VAR11'].fillna(train_data['VAR11'].median(),inplace=True)
train_data['VAR12'].fillna(train_data['VAR12'].median(),inplace=True)
train_data['VAR13'].fillna(train_data['VAR13'].median(),inplace=True)
train_data['VAR15'].fillna(train_data['VAR15'].median(),inplace=True)
train_data['VAR16'].fillna(train_data['VAR16'].median(),inplace=True) 
train_data['VAR14']= train_data['VAR14'].astype('str') 
train_data['VAR14']=train_data['VAR14'].replace('.','1')
train_data['VAR14']= train_data['VAR14'].astype('int64') 

In [8]:
train_data.head()

VAR1        VAR2      VAR3        VAR4        VAR5      VAR6      VAR7  \
0     1  828.235294  0.138889  321.428571  625.911006  1.818182  1.081550   
1     2  911.764706  0.027778  142.857143  611.574748  8.181818  1.344479   
2     3  962.352941  0.833333   35.714286  615.825381  8.181818  0.720796   
3     4  892.941177  0.166667  142.857143  638.076431  9.090909  0.820218   
4     5  914.117647  0.083333  142.857143  626.514988  5.181818  1.372928   

         VAR8       VAR9      VAR10  ...       VAR12  VAR13  VAR14  VAR15  \
0  198.113469  22.086661  58.632548  ...  100.083403    1.0      1    1.0   
1  198.600020  22.086661  58.632548  ...   15.012510   10.0      1   10.0   
2  197.267767  22.086661  58.632548  ...  210.175146   10.0      1   10.0   
3  197.355744   4.363431  58.632548  ...   80.066722   10.0      1   10.0   
4  198.790477  85.938202  58.632548  ...  210.175146   10.0      1   10.0   

      VAR16  VAR17  VAR18  VAR19       VAR20   VAR21  
0  1.540594    NaN      1      0  100.104991     Low  
1  1.614613    NaN      0      1  146.654045    High  
2  1.044599    NaN      0      0   98.249570  Medium  
3  1.145729    NaN      1      0  140.862306     Low  
4  1.558341    NaN      1      0  101.268503    High  

[5 rows x 21 columns]

In [9]:
nvars=['VAR2','VAR3','VAR4','VAR5','VAR6','VAR7','VAR8','VAR9','VAR10','VAR11','VAR12','VAR13','VAR14','VAR15','VAR16','VAR18','VAR19','VAR20']
X=train_data[nvars]
Y=train_data['VAR21']

In [10]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
transfomed_label = encoder.fit_transform(Y)
print(transfomed_label)

[[0 1 0]
 [1 0 0]
 [0 0 1]
 ...
 [0 1 0]
 [0 1 0]
 [1 0 0]]


In [11]:
xtrain, xvalid, ytrain, yvalid = train_test_split(X,Y, random_state=42, test_size=0.2)

In [12]:
train_data['VAR21'].value_counts()

Medium    18172
Low       12081
High       3747
Name: VAR21, dtype: int64

In [16]:
from sklearn.ensemble import GradientBoostingClassifier#best results so far from Gradient boost
model = GradientBoostingClassifier(learning_rate=0.1,max_depth=5)
model.fit(xtrain, ytrain)
pred = model.predict(xvalid)
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(yvalid, pred))
print(classification_report(yvalid, pred))

[[  59  123  577]
 [  21  907 1460]
 [  40  627 2986]]
              precision    recall  f1-score   support

        High       0.49      0.08      0.13       759
         Low       0.55      0.38      0.45      2388
      Medium       0.59      0.82      0.69      3653

    accuracy                           0.58      6800
   macro avg       0.54      0.42      0.42      6800
weighted avg       0.57      0.58      0.54      6800



In [14]:
#model = LogisticRegression(solver = 'lbfgs')
#model.fit(xtrain, ytrain)

C:\Users\neera\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\neera\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\neera\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\neera\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
prediction = model.predict_proba(xvalid)
prediction_int = prediction.astype(np.int)
encoder.inverse_transform(prediction)
model.score(xvalid, yvalid)

0.5811764705882353

In [18]:
#from sklearn import svm
#model = svm.SVC(gamma='scale',decision_function_shape='ovo')
#model.fit(xtrain, ytrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
train_data.dtypes

VAR1       int64
VAR2     float64
VAR3     float64
VAR4     float64
VAR5     float64
VAR6     float64
VAR7     float64
VAR8     float64
VAR9     float64
VAR10    float64
VAR11    float64
VAR12    float64
VAR13    float64
VAR14      int64
VAR15    float64
VAR16    float64
VAR17    float64
VAR18      int64
VAR19      int64
VAR20    float64
VAR21     object
dtype: object

In [20]:
#from sklearn.neighbors import KNeighborsClassifier
#model = KNeighborsClassifier(n_neighbors = 3)
#model.fit(xtrain, ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [21]:
#from sklearn.ensemble import RandomForestClassifier
#model=RandomForestClassifier()
#model.fit(xtrain,ytrain)

C:\Users\neera\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [22]:
leader_data.isnull().sum()

VAR1        0
VAR2      267
VAR3      937
VAR4     3686
VAR5        0
VAR6     1058
VAR7      215
VAR8      215
VAR9     4701
VAR10    1348
VAR11    2231
VAR12    3201
VAR13    2493
VAR14       0
VAR15    2359
VAR16     229
VAR17    6543
VAR18       0
VAR19       0
VAR20       0
dtype: int64

In [23]:
leader_data['VAR2'].fillna(train_data['VAR2'],inplace=True)
leader_data['VAR3'].fillna(train_data['VAR3'],inplace=True)
leader_data['VAR4'].fillna(train_data['VAR4'],inplace=True)
leader_data['VAR5'].fillna(train_data['VAR5'],inplace=True)
leader_data['VAR6'].fillna(train_data['VAR6'],inplace=True)
leader_data['VAR7'].fillna(train_data['VAR7'],inplace=True)
leader_data['VAR8'].fillna(train_data['VAR8'],inplace=True)
leader_data['VAR9'].fillna(train_data['VAR9'],inplace=True)
leader_data['VAR10'].fillna(train_data['VAR10'],inplace=True)
leader_data['VAR11'].fillna(train_data['VAR11'],inplace=True)
leader_data['VAR12'].fillna(train_data['VAR12'],inplace=True)
leader_data['VAR13'].fillna(train_data['VAR13'],inplace=True)
leader_data['VAR15'].fillna(train_data['VAR15'],inplace=True)
leader_data['VAR16'].fillna(train_data['VAR16'],inplace=True)
leader_data['VAR14']= train_data['VAR14'].astype('str') 
leader_data['VAR14']=train_data['VAR14'].replace('.','1')
leader_data['VAR14']= train_data['VAR14'].astype('int64') 

In [24]:
Xtest=leader_data[nvars]

In [25]:
test_pred=model.predict_proba(Xtest)

In [26]:
test_pred == test_pred.max(axis=1)[:,None].astype(np.int)
enp=encoder.inverse_transform(test_pred)

In [27]:
Submission = pd.DataFrame({'VAR1':leader_data['VAR1'],'VAR21':enp})
Submission.to_csv("ATeam _IITGuwahati_1.csv", index=False)

In [28]:
train_data['VAR14'].value_counts()

1      21089
2       7965
3       2796
4        910
0        756
5        269
6        117
7         31
8         26
10        14
12         9
9          8
15         2
11         2
23         1
22         1
14         1
18         1
20         1
104        1
Name: VAR14, dtype: int64